import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import rc
rc('font',**{'family':'sans-serif','serif':['Computer Modern Roman'],'sans-serif':['Helvetica']})
rc('text', usetex=True)
matplotlib.rcParams['text.usetex'] = True
import os

file_path = os.path.dirname(os.path.abspath(__file__))
epsilon_RT_alpha_02 = np.linspace(0, 1, 11)

folder = 'evolution_over_epsilon'
u = np.load(os.path.join(file_path, 'data', folder ,'steady_states.npy'))

fig1 = plt.figure(1)
plt.scatter(epsilon_RT_alpha_02, u[:,0]*10e-3, color = 'black', label = r'$\displaystyle uninfected \; T \; cells$')
plt.grid()
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'$\displaystyle T(t) \; [cells/\mu l]$', labelpad=10, fontsize=18)
plt.tick_params(labelsize=16)
plt.tight_layout()
plt.savefig(os.path.join('images',folder,'treated_T.pdf'), dpi = 300, pad_inches=0.25)
plt.show()

fig2 = plt.figure(2)
plt.yscale('log')
plt.scatter(epsilon_RT_alpha_02, u[:,1], color= 'black', label = 'Ts')
plt.grid()
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'$\displaystyle T_s(t) \; [log_{10}(cells/ml^3)]$', labelpad=10, fontsize=18)
plt.tick_params(labelsize=16)
plt.tight_layout()
plt.savefig(os.path.join('images',folder,'treated_Ts.pdf'), dpi = 300, pad_inches=0.25)
plt.show()

fig3 = plt.figure(3)
plt.yscale('log')
plt.scatter(epsilon_RT_alpha_02, u[:,3], color= 'black', label = 'Vs')
plt.grid()
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'$\displaystyle V_s(t) \; [log_{10}(cells/ml^3)]$', labelpad=10, fontsize=18)
plt.tick_params(labelsize=16)
plt.tight_layout()
plt.savefig(os.path.join('images',folder,'treated_Vs.pdf'), dpi = 300, pad_inches=0.25)
plt.show()

# plt.subplot(3,1,3)
fig4 = plt.figure(4)
plt.yscale('log')
plt.scatter(epsilon_RT_alpha_02, u[:,2], color= 'black', label = 'Tr')
plt.grid()
# plt.legend()
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'$\displaystyle T_r(t) \; [log_{10}(cells/ml^3)]$', labelpad=10, fontsize=18)
plt.tight_layout()
plt.tick_params(labelsize=16)
plt.savefig(os.path.join('images',folder,'treated_Tr.pdf'), dpi = 300, pad_inches=0.25)
plt.show()

fig5 = plt.figure(5)
plt.yscale('log')
plt.scatter(epsilon_RT_alpha_02, u[:,4], color= 'black', label = 'Vr')
plt.grid()
# plt.xlim((0, 400))
# plt.ylim((-15, 5))
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'$\displaystyle V_r(t) \; [log_{10}(cells/ml^3)]$', labelpad=10, fontsize=18)
plt.tick_params(labelsize=16)
plt.tight_layout()
plt.savefig(os.path.join('images',folder,'treated_Vr.pdf'), dpi = 300, pad_inches=0.25)
plt.show()

fig6 = plt.figure(6)
plt.yscale('log')
plt.scatter(epsilon_RT_alpha_02, u[:,3] + u[:,4], color= 'black', label = 'Vr')
plt.grid()
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'$\displaystyle V_r(t)+V_s(t) \; [log_{10}(cells/ml^3)]$', labelpad=10, fontsize=18)
plt.tick_params(labelsize=16)
plt.tight_layout()
plt.savefig(os.path.join('images',folder,'treated_total_V.pdf'), dpi = 300, pad_inches=0.25)
plt.show()

fig7 = plt.figure(7)
# plt.yscale('log')
plt.scatter(epsilon_RT_alpha_02, u[:,3] + u[:,4], color = '0.65', s = 80, label = '$\displaystyle V_r + V_s$')
plt.scatter(epsilon_RT_alpha_02, u[:,3], color = 'black',marker = 'x', label = '$\displaystyle V_s$')
plt.scatter(epsilon_RT_alpha_02, u[:,4], color = 'black', marker = '<',label = '$\displaystyle V_r$')
plt.grid()
plt.legend(loc = 'upper right', fontsize = 16)
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'viral cell concentration $[cells/ml^3]$', labelpad=10, fontsize=18)
plt.tick_params(labelsize=16)
plt.tight_layout()
plt.savefig(os.path.join('images',folder,'treated_overview_V.pdf'), dpi = 300, pad_inches=0.25)
plt.show()

fig8 = plt.figure(8)
# plt.yscale('log')
plt.scatter(epsilon_RT_alpha_02, u[:,2] + u[:,1], color = '0.65', s = 80, label = '$\displaystyle T_r + T_s$')
plt.scatter(epsilon_RT_alpha_02, u[:,1], color = 'black', marker = 'x', label = '$\displaystyle T_s$')
plt.scatter(epsilon_RT_alpha_02, u[:,2], color = 'black', marker = '<', label = '$\displaystyle T_r$')
plt.grid()
plt.legend(loc = 'upper right', fontsize = 16)
# plt.ylim((-10, 10))
plt.xlabel(r'$\displaystyle \varepsilon_s \; [1]$', labelpad=10, fontsize = 18)
plt.ylabel(r'immune cell concentration $[cells/ml^3]$', labelpad=10, fontsize=18)
plt.tick_params(labelsize=16)
plt.tight_layout()
plt.savefig(os.path.join('images',folder,'treated_overview_infected_T.pdf'), dpi = 300, pad_inches=0.25)
plt.show()